#!/bin/sh


# Cleanup previous build files
rm -rf obj_dir
rm -f sigdelay.vcd

verilator -Wall --cc --trace sigdelay.sv ram2ports.sv counter.sv --exe sigdelay_tb.cpp --top-module sigdelay
# verilator -Wall --cc --trace sigdelay.sv ram2ports.sv counter.sv --exe sigdelay_tb.cpp -Mdir obj_dir --top-module sigdelay --CFLAGS "-std=c++17"

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsigdelay.mk Vsigdelay

# Run the executable simulation file
obj_dir/Vsigdelay
